# Generated by Django 3.1.5 on 2022-12-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invitor_color',
            field=models.CharField(choices=[('black', 'Czarny'), ('white', 'Biały'), ('random', 'Losowy')], max_length=32),
        ),
    ]
