# Generated by Django 3.1.5 on 2022-12-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_aigame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aigame',
            old_name='fen',
            new_name='pgn',
        ),
    ]
