# Generated by Django 3.1.5 on 2022-12-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess', '0007_onlinegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinegame',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerwhite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerblack', to=settings.AUTH_USER_MODEL),
        ),
    ]
