# Generated by Django 3.1.5 on 2022-12-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_auto_20221214_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invitor_color',
            field=models.CharField(choices=[('black', 'Czarny'), ('white', 'Biały'), ('random', 'Losowy')], max_length=32, verbose_name='twój kolor'),
        ),
    ]
